[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction'
]

[start]
cmd = 'php artisan config:clear && php -S 0.0.0.0:$PORT -t public'
